version: "3.9"
services:
  server:
    image: ghcr.io/zhongfuze/id_allocation:main
    container_name: id_allocation
    volumes:
      - ./shared_data:/app/data
      - ./app/config:/app/config
      - ./app/log_tmp:/tmp
      - ./app/log:/app/log
    network_mode: "host"
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ~/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/app/nginx/conf.d:/etc/nginx/conf.d
      - ~/app/nginx/logs:/var/log/nginx
      - ~/app/nginx/ssl:/etc/ssl
    network_mode: "host"